export type Category = "all" | "whitening" | "brushes" | "toothpaste" | "kits";

export interface Product {
  id: string;
  name: string;
  description: string;
  category: Exclude<Category, "all">;
  badge?: "BEST SELLER" | "NEW LAUNCH" | "TOP RATED";
  rating: number;
  reviews: string;
  price: number;
  originalPrice: number;
  variants: string[];
  img: string;
  featured?: boolean;
  featuredBenefits?: string[];
}

const CDN = "https://cdn.shopify.com/s/files/1/0587/1036/0271/files";

export const PRODUCTS: Product[] = [
  {
    id: "whitening-serum",
    name: "Purple Magic Teeth Whitening Serum",
    description: "Get 2× Whiter Teeth in 2 Weeks with clinically proven colour-corrective serum.",
    category: "whitening",
    badge: "BEST SELLER",
    rating: 4.2,
    reviews: "42,000",
    price: 898,
    originalPrice: 1299,
    variants: ["Pack of 1 – 30 Days", "Pack of 2 – 60 Days"],
    img: `${CDN}/Purple_Serum_30_ml.webp?v=1760358264`,
    featured: true,
    featuredBenefits: [
      "Safe for Sensitive Teeth (Peroxide Free)",
      "2 Month Supply — Just ₹449 per use",
      "Clinically proven colour correction",
      "No sensitivity, no fuss",
    ],
  },
  {
    id: "whitening-strips-14",
    name: "Teeth Whitening Strips — Pack of 14",
    description: "Classic Mint | 28 Strips | 14 Days Treatment",
    category: "whitening",
    badge: "NEW LAUNCH",
    rating: 4.5,
    reviews: "180",
    price: 898,
    originalPrice: 1349,
    variants: ["Pack of 2 – 60 Days", "Pack of 3 – 90 Days"],
    img: `${CDN}/Teeth_Whitening_Strips_Listing_Image_1.jpg?v=1775811132`,
  },
  {
    id: "whitening-strips-28",
    name: "Teeth Whitening Strips — Pack of 28",
    description: "Spearmint | 56 Strips | 28 Days Treatment",
    category: "whitening",
    badge: "BEST SELLER",
    rating: 4.5,
    reviews: "320",
    price: 898,
    originalPrice: 1349,
    variants: ["Pack of 2 – 60 Days", "Pack of 3 – 90 Days"],
    img: `${CDN}/Teeth_Whitening_Strips_Listing_Image_2.jpg?v=1775811132`,
  },
  {
    id: "whitening-strips-trial",
    name: "Teeth Whitening Strips — Trial Pack",
    description: "Classic Mint | 6 Strips | 3 Days Treatment",
    category: "whitening",
    rating: 4.5,
    reviews: "204",
    price: 349,
    originalPrice: 599,
    variants: ["Pack of 1 – Trial", "Pack of 2"],
    img: `${CDN}/Teeth_Whitening_Strips_Listing_Image_Trial.jpg?v=1776062224`,
  },
  {
    id: "whitening-strips-combo",
    name: "Teeth Whitening Strips & Serum Combo",
    description: "Best value — Strips + Purple Serum in one kit",
    category: "whitening",
    badge: "BEST SELLER",
    rating: 4.6,
    reviews: "1.2K",
    price: 999,
    originalPrice: 1599,
    variants: ["Standard Combo", "Premium Combo"],
    img: `${CDN}/WhatsApp_Image_2026-04-09_at_15.34.46.jpg?v=1775729205`,
  },
  {
    id: "whitening-kit",
    name: "Teeth Whitening Essentials Combo",
    description: "Complete whitening system — serum + strips + toothpaste",
    category: "whitening",
    badge: "TOP RATED",
    rating: 4.7,
    reviews: "890",
    price: 980,
    originalPrice: 1600,
    variants: ["Standard Kit", "Premium Kit"],
    img: `${CDN}/Teeth_Whitening_Essentials_Combo.jpg?v=1776764627`,
  },
  {
    id: "smart-sonic-etb",
    name: "Smart Sonic Electric Toothbrush — Rechargeable",
    description: "Bluetooth Connected | 5 Modes | 2-Year Warranty",
    category: "brushes",
    badge: "BEST SELLER",
    rating: 4.7,
    reviews: "5.1K",
    price: 2999,
    originalPrice: 3499,
    variants: ["Midnight Black", "Pearl White"],
    img: `${CDN}/Sonic_Black_With_Box.webp?v=1765283015`,
  },
  {
    id: "etb-m001-rechargeable",
    name: "Electric Toothbrush M001 — Rechargeable",
    description: "USB Rechargeable | 4 Speed Modes | 40,000 strokes/min",
    category: "brushes",
    badge: "TOP RATED",
    rating: 4.6,
    reviews: "8.4K",
    price: 1399,
    originalPrice: 1999,
    variants: ["Charcoal Grey", "Arctic White"],
    img: `${CDN}/Charcoal_Grey_Model001_with_brushhead.webp?v=1755088427`,
  },
  {
    id: "oscillating-etb",
    name: "Limitless Black Oscillating Toothbrush — Rechargeable",
    description: "Dentist-grade oscillating action | With Brush Heads | 2-Year Warranty",
    category: "brushes",
    badge: "NEW LAUNCH",
    rating: 4.7,
    reviews: "640",
    price: 2158,
    originalPrice: 2999,
    variants: ["Limitless Black"],
    img: `${CDN}/Oscillating_Toothbrush_with_brushheads.webp?v=1762342462`,
  },
  {
    id: "purple-magic-paste",
    name: "Purple Magic Whitening Toothpaste",
    description: "Colour-correcting formula | Fluoride-free | Fresh mint",
    category: "toothpaste",
    badge: "BEST SELLER",
    rating: 4.4,
    reviews: "6.2K",
    price: 299,
    originalPrice: 399,
    variants: ["125g", "125g × 3"],
    img: `${CDN}/Purple_Magic_Toothpaste_Po1.webp?v=1762498657`,
  },
  {
    id: "dream-white-paste",
    name: "Dream White — Teeth Whitening Toothpaste",
    description: "Advanced whitening formula | Enamel safe | Fresh breath",
    category: "toothpaste",
    badge: "TOP RATED",
    rating: 4.5,
    reviews: "3.8K",
    price: 468,
    originalPrice: 532,
    variants: ["Pack of 1", "Pack of 2", "Pack of 3"],
    img: `${CDN}/DreamWhite_Pack_of_1.jpg?v=1776684230`,
  },
  {
    id: "charcoal-paste",
    name: "Activated Charcoal Toothpaste",
    description: "Deep clean | Detoxifying | Natural whitening",
    category: "toothpaste",
    rating: 4.3,
    reviews: "2.1K",
    price: 266,
    originalPrice: 349,
    variants: ["Pack of 1", "Pack of 2", "Pack of 3"],
    img: `${CDN}/Charcoal_Toothpaste_Pack_of_2.jpg?v=1774270807`,
  },
  {
    id: "power-flosser",
    name: "Power Dental Flosser",
    description: "Wireless & Waterproof · 3 Pressure Modes · 2-Year Warranty",
    category: "kits",
    badge: "BEST SELLER",
    rating: 4.7,
    reviews: "12K",
    price: 2089,
    originalPrice: 2699,
    variants: ["Sterling Grey", "Arctic White"],
    img: `${CDN}/002_1_2f8391cd-3b3a-4c6b-a5ee-b8c722a098ce.webp?v=1771869727`,
  },
  {
    id: "smart-flosser",
    name: "Smart Dental Flosser — Black Gold",
    description: "Premium water flosser | 3 modes | 2-Year Warranty",
    category: "kits",
    badge: "TOP RATED",
    rating: 4.8,
    reviews: "3.4K",
    price: 3039,
    originalPrice: 3599,
    variants: ["Black Gold"],
    img: `${CDN}/Smart_flosser_Mock_black.webp?v=1743153037`,
  },
  {
    id: "purple-whitening-kit",
    name: "Purple Whitening Kit",
    description: "Complete whitening system — serum + toothpaste + accessories",
    category: "kits",
    badge: "NEW LAUNCH",
    rating: 4.6,
    reviews: "1.8K",
    price: 899,
    originalPrice: 1222,
    variants: ["Standard Kit", "Premium Kit"],
    img: `${CDN}/Purple_Care_Kit_1.jpg?v=1777973828`,
  },
];

export const TRUST_BADGES = [
  { icon: "🧪", label: "CLINICALLY TESTED" },
  { icon: "🌿", label: "FLUORIDE-FREE" },
  { icon: "✦", label: "ENAMEL SAFE" },
  { icon: "🦷", label: "DENTIST FORMULATED" },
  { icon: "🏠", label: "AT-HOME WHITENING" },
  { icon: "⭐", label: "VISIBLE RESULTS IN 2 WEEKS" },
];

export const SORT_OPTIONS = [
  { value: "best-selling", label: "Best Selling" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "top-rated", label: "Top Rated" },
  { value: "newest", label: "Newest" },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Priya A.",
    verified: true,
    rating: 5,
    text: "We started actually committing on how clean my teeth were by my dentist. She asked what changed — I told her I switched to Perfora. Mind blown.",
    product: "Electric Toothbrush",
    avatar: "P",
  },
  {
    id: 2,
    name: "Rohan K.",
    verified: true,
    rating: 4,
    text: "I was skeptical about it being whitening but the results after 7 days genuinely surprised me. No sensitivity whatsoever and my smile looks noticeably brighter.",
    product: "Whitening Strips",
    avatar: "R",
  },
  {
    id: 3,
    name: "Sneha R.",
    verified: true,
    rating: 5,
    text: "This glossy Pro routine fits my lifestyle so perfectly. Friends have been asking me about my teeth. I finally feel confident smiling in photos.",
    product: "Teeth Whitening Serum",
    avatar: "S",
  },
];

export const FAQS = [
  { q: "Why should I use this serum?", a: "Our Purple Magic Serum uses colour-correcting technology to neutralise yellow tones instantly, while a gentle whitening formula delivers visible results within 2 weeks — without any sensitivity." },
  { q: "How does the Purple Serum help in teeth whitening?", a: "The serum contains micro-whitening agents that break down surface stains and a purple pigment that colour-corrects yellowing on contact, giving you an instant brighter appearance." },
  { q: "How long does it take to show results?", a: "Most customers see noticeable results within 7–14 days of consistent use. For best results, use twice daily as part of your brushing routine." },
  { q: "Is a serum used in Oral care?", a: "Yes! Oral serums are a growing category in dental hygiene. Applied after brushing, they deliver concentrated active ingredients directly to your enamel for targeted results." },
  { q: "Are there any side effects of it?", a: "Our formula is peroxide-free and clinically tested for sensitive teeth. It is free from fluoride, SLS, and parabens. Discontinue use if irritation occurs." },
  { q: "Can children use this?", a: "This product is formulated for adults (18+). For children, we recommend our dedicated Kids range." },
];
