export type Category = "all" | "whitening" | "brushes" | "toothpaste" | "kits";

export interface Product {
  id: string;
  name: string;
  description: string;
  category: Exclude<Category, "all">;
  badge?: "BEST SELLER" | "NEW LAUNCH" | "TOP RATED";
  rating: number;
  reviews: string;
  price: number;
  originalPrice: number;
  variants: string[];
  featured?: boolean;
  featuredBenefits?: string[];
}

export const PRODUCTS: Product[] = [
  {
    id: "whitening-serum",
    name: "Purple Magic Teeth Whitening Serum",
    description: "Get 2× Whiter Teeth in 2 Weeks with clinically proven colour-corrective serum.",
    category: "whitening",
    badge: "BEST SELLER",
    rating: 4.2,
    reviews: "42,000",
    price: 898,
    originalPrice: 1299,
    variants: ["Pack of 1 – 30 Days", "Pack of 2 – 60 Days"],
    featured: true,
    featuredBenefits: [
      "Safe for Sensitive Teeth (Peroxide Free)",
      "2 Month Supply — Just ₹449 per use",
      "Clinically proven colour correction",
      "No sensitivity, no fuss",
    ],
  },
  {
    id: "whitening-strips-14",
    name: "Teeth Whitening Strips — Pack of 14",
    description: "Classic Mint | 28 Strips | 14 Days Treatment",
    category: "whitening",
    badge: "NEW LAUNCH",
    rating: 4.5,
    reviews: "180",
    price: 799,
    originalPrice: 999,
    variants: ["Pack of 2 – 60 Days", "Pack of 3 – 90 Days"],
  },
  {
    id: "whitening-strips-28",
    name: "Teeth Whitening Strips — Pack of 28",
    description: "Spearmint | 56 Strips | 28 Days Treatment",
    category: "whitening",
    badge: "BEST SELLER",
    rating: 4.5,
    reviews: "320",
    price: 898,
    originalPrice: 1349,
    variants: ["Pack of 2 – 60 Days", "Pack of 3 – 90 Days"],
  },
  {
    id: "whitening-strips-premium",
    name: "Tooth Whitening Strips — Premium",
    description: "Coconut Mint | 28 Strips | 14 Days Treatment",
    category: "whitening",
    rating: 4.5,
    reviews: "204",
    price: 898,
    originalPrice: 1349,
    variants: ["Pack of 2 – 60 Days", "Pack of 3 – 90 Days"],
  },
  {
    id: "whitening-powder",
    name: "Activated Charcoal Whitening Powder",
    description: "Natural whitening with activated charcoal & coconut oil",
    category: "whitening",
    badge: "TOP RATED",
    rating: 4.3,
    reviews: "890",
    price: 499,
    originalPrice: 699,
    variants: ["50g", "100g"],
  },
  {
    id: "whitening-kit",
    name: "Complete Whitening Starter Kit",
    description: "Serum + Strips + Powder — everything you need",
    category: "whitening",
    badge: "BEST SELLER",
    rating: 4.6,
    reviews: "1.2K",
    price: 1799,
    originalPrice: 2499,
    variants: ["Standard Kit", "Premium Kit"],
  },
  {
    id: "etb-model-001",
    name: "Sonic Electric Toothbrush — Model 001",
    description: "AAA Battery | 3 Speed Modes | 30,000 strokes/min",
    category: "brushes",
    badge: "BEST SELLER",
    rating: 4.6,
    reviews: "8.4K",
    price: 799,
    originalPrice: 1299,
    variants: ["Midnight Black", "Arctic White", "Lavender"],
  },
  {
    id: "etb-model-005",
    name: "Sonic Electric Toothbrush — Rechargeable 005",
    description: "USB Rechargeable | 4 Speed Modes | 40,000 strokes/min",
    category: "brushes",
    badge: "TOP RATED",
    rating: 4.7,
    reviews: "5.1K",
    price: 1499,
    originalPrice: 1999,
    variants: ["Midnight Black", "Arctic White"],
  },
  {
    id: "smart-sonic-etb",
    name: "Smart Sonic Electric Toothbrush",
    description: "Bluetooth Connected | 5 Modes | 2-Year Warranty",
    category: "brushes",
    rating: 4.8,
    reviews: "2.3K",
    price: 2499,
    originalPrice: 3499,
    variants: ["Gunmetal Grey", "Pearl White"],
  },
  {
    id: "oscillating-etb",
    name: "Oscillating Electric Toothbrush",
    description: "Dentist-grade oscillating action | 2-Year Warranty",
    category: "brushes",
    badge: "NEW LAUNCH",
    rating: 4.7,
    reviews: "640",
    price: 2999,
    originalPrice: 3999,
    variants: ["Midnight Black", "Pearl White"],
  },
  {
    id: "purple-magic-paste",
    name: "Purple Magic Teeth Whitening Toothpaste",
    description: "Colour-correcting formula | Fluoride-free | Fresh mint",
    category: "toothpaste",
    badge: "BEST SELLER",
    rating: 4.4,
    reviews: "6.2K",
    price: 349,
    originalPrice: 449,
    variants: ["75ml", "75ml × 2"],
  },
  {
    id: "sensitive-paste",
    name: "Sensitive Care Toothpaste",
    description: "Gentle on enamel | Potassium nitrate formula",
    category: "toothpaste",
    badge: "TOP RATED",
    rating: 4.5,
    reviews: "3.8K",
    price: 299,
    originalPrice: 399,
    variants: ["75ml", "75ml × 2", "75ml × 3"],
  },
  {
    id: "charcoal-paste",
    name: "Activated Charcoal Toothpaste",
    description: "Deep clean | Detoxifying | Natural whitening",
    category: "toothpaste",
    rating: 4.3,
    reviews: "2.1K",
    price: 279,
    originalPrice: 349,
    variants: ["75ml", "75ml × 2"],
  },
  {
    id: "power-flosser",
    name: "Power Dental Flosser",
    description: "Wireless & Waterproof · 3 Pressure Modes · 2-Year Warranty",
    category: "kits",
    badge: "BEST SELLER",
    rating: 4.7,
    reviews: "12K",
    price: 2499,
    originalPrice: 2999,
    variants: ["Sterling Grey", "Arctic White"],
  },
  {
    id: "daily-essentials-kit",
    name: "Daily Essentials Kit",
    description: "ETB + Toothpaste + Floss Picks — your complete daily routine",
    category: "kits",
    badge: "BEST SELLER",
    rating: 4.6,
    reviews: "3.4K",
    price: 1299,
    originalPrice: 1999,
    variants: ["Standard", "Premium"],
  },
  {
    id: "complete-care-kit",
    name: "Complete Oral Care Bundle",
    description: "ETB + Whitening Serum + Toothpaste + Flosser",
    category: "kits",
    badge: "TOP RATED",
    rating: 4.8,
    reviews: "1.8K",
    price: 3499,
    originalPrice: 5499,
    variants: ["Classic Bundle", "Premium Bundle"],
  },
];

export const TRUST_BADGES = [
  "CLINICALLY TESTED",
  "FLUORIDE-FREE",
  "ENAMEL SAFE",
  "DENTIST FORMULATED",
  "AT-HOME WHITENING",
  "VISIBLE RESULTS IN 2 WEEKS",
];

export const SORT_OPTIONS = [
  { value: "best-selling", label: "Best Selling" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "top-rated", label: "Top Rated" },
  { value: "newest", label: "Newest" },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Priya A.",
    verified: true,
    rating: 5,
    text: "We started actually committing on how clean my teeth were by my dentist. She asked what changed — I told her I switched to Perfora. Mind blown.",
    product: "Electric Toothbrush",
  },
  {
    id: 2,
    name: "Rohan K.",
    verified: true,
    rating: 4,
    text: "I was skeptical about it being whitening but the results after 7 days genuinely surprised me. No sensitivity whatsoever and my smile looks noticeably brighter.",
    product: "Whitening Strips",
  },
  {
    id: 3,
    name: "Sneha R.",
    verified: true,
    rating: 5,
    text: "This glossy Pro routine fits my lifestyle so perfectly. Friends have been asking me about my teeth. I finally feel confident smiling in photos.",
    product: "Teeth Whitening Serum",
  },
];

export const FAQS = [
  { q: "Why should I use this serum?", a: "Our Purple Magic Serum uses colour-correcting technology to neutralise yellow tones instantly, while a gentle whitening formula delivers visible results within 2 weeks — without any sensitivity." },
  { q: "How does the Purple Serum help in teeth whitening?", a: "The serum contains micro-whitening agents that break down surface stains and a purple pigment that colour-corrects yellowing on contact, giving you an instant brighter appearance." },
  { q: "How long does it take to show results?", a: "Most customers see noticeable results within 7–14 days of consistent use. For best results, use twice daily as part of your brushing routine." },
  { q: "Is a serum used in Oral care?", a: "Yes! Oral serums are a growing category in dental hygiene. Applied after brushing, they deliver concentrated active ingredients directly to your enamel for targeted results." },
  { q: "Are there any side effects of it?", a: "Our formula is peroxide-free and clinically tested for sensitive teeth. It is free from fluoride, SLS, and parabens. As with any oral care product, discontinue use if irritation occurs." },
  { q: "How does the Purple Serum taste?", a: "It has a pleasant cool mint flavour that leaves your mouth feeling fresh and clean after every use." },
  { q: "Can children use this?", a: "This product is formulated for adults (18+). For children, we recommend our dedicated Kids range." },
];
